name = "ag-ui-worker"
compatibility_date = "2024-01-01"
main = "worker.js"

[build]
command = "wasm-pack build --target web --out-dir ./pkg"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true 